//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CertifiedLabel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CECase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CECase()
        {
            this.CELetters = new HashSet<CELetter>();
        }
    
        public Nullable<System.DateTime> dateEntered { get; set; }
        public string EnteredBy { get; set; }
        public Nullable<int> CV_INSERT_IDENTITY { get; set; }
        public Nullable<int> ParentID { get; set; }
        public int RecordID { get; set; }
        public string Address { get; set; }
        public byte[] C_TimeStamp { get; set; }
        public string RequestType { get; set; }
        public string Folio { get; set; }
        public string TrackingNumber { get; set; }
        public string BLK2000ID { get; set; }
        public Nullable<int> CESECTID { get; set; }
        public Nullable<int> CEZNID { get; set; }
        public Nullable<System.DateTime> dateReceived { get; set; }
        public string CaseNumber { get; set; }
        public string Type { get; set; }
        public string Priority { get; set; }
        public Nullable<short> NetID { get; set; }
        public string Location { get; set; }
        public string Source { get; set; }
        public string Status { get; set; }
        public string Inspector { get; set; }
        public Nullable<bool> FlagROW { get; set; }
        public Nullable<System.DateTime> dateFirstInspection { get; set; }
        public Nullable<System.DateTime> dateInspectorAssigned { get; set; }
        public Nullable<System.DateTime> dateLastAction { get; set; }
        public Nullable<System.DateTime> dateClosed { get; set; }
        public string SourceDetails { get; set; }
        public string ParentCase { get; set; }
        public Nullable<decimal> PerDiem { get; set; }
        public Nullable<bool> FlagRepeat { get; set; }
        public string Description { get; set; }
        public Nullable<int> YrlyLotProcessNumber { get; set; }
        public Nullable<System.DateTime> dateService { get; set; }
        public Nullable<bool> flagLegacy { get; set; }
        public Nullable<System.DateTime> dateComplianceDue { get; set; }
        public Nullable<System.DateTime> dateInCompliance { get; set; }
        public string HistoricalCaseNumber { get; set; }
        public string RequestCategory { get; set; }
        public Nullable<System.DateTime> datePerDiem { get; set; }
        public string TicketNumber { get; set; }
        public string ReferTo { get; set; }
        public Nullable<bool> flagPerDiem { get; set; }
        public string TypeChangeReason { get; set; }
        public string CSRProcessMessage { get; set; }
        public string flagCSRProcessOK { get; set; }
        public string flagCSRReady { get; set; }
        public string STUNIT { get; set; }
        public Nullable<int> STNUMBER { get; set; }
        public string STTYPE { get; set; }
        public string STNAME { get; set; }
        public Nullable<int> CustID { get; set; }
        public Nullable<bool> flagNotGeoInspector { get; set; }
        public Nullable<bool> flagCertifyOK { get; set; }
        public string Compare { get; set; }
        public string Division { get; set; }
        public string LawCaseNumber { get; set; }
        public Nullable<bool> flagIsRegistered { get; set; }
        public Nullable<bool> flagLotIsRegistered { get; set; }
        public Nullable<int> TotalYards { get; set; }
        public Nullable<int> NumberContainers { get; set; }
        public Nullable<int> HaulerCompany { get; set; }
        public Nullable<int> OldCustID { get; set; }
        public string FPBCUID { get; set; }
        public string BD4050ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CELetter> CELetters { get; set; }
        public virtual LookupEmployee LookupEmployee { get; set; }
        public virtual LookupEmployee LookupEmployee1 { get; set; }
    }
}
