//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CertifiedLabel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CELetterRecipient
    {
        public string SignatureRight { get; set; }
        public string Body { get; set; }
        public Nullable<int> CELetterID { get; set; }
        public string SignatureLeft { get; set; }
        public string HeaderLeft { get; set; }
        public string HeaderRight { get; set; }
        public Nullable<int> CV_INSERT_IDENTITY { get; set; }
        public string Footer { get; set; }
        public int RecordID { get; set; }
        public byte[] C_TimeStamp { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DatePrinted { get; set; }
        public string PrintStatus { get; set; }
        public string EnteredBy { get; set; }
        public Nullable<System.DateTime> dateEntered { get; set; }
        public Nullable<System.DateTime> dateReprinted { get; set; }
        public string DeliveryMethod { get; set; }
        public Nullable<bool> flagReprint { get; set; }
        public string InspectorNote { get; set; }
        public string CertifiedNumber { get; set; }
        public string BusinessName { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string City { get; set; }
        public string Address1 { get; set; }
        public string Zip { get; set; }
        public string Address2 { get; set; }
        public Nullable<int> CEPropertyContactID { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> dateGenerated { get; set; }
        public string DigitalSignatureLeft { get; set; }
        public string TransferredTo { get; set; }
        public Nullable<System.DateTime> DateFieldPrint { get; set; }
        public Nullable<System.DateTime> DateGreenCardReceived { get; set; }
        public string DigitalSignatureRight { get; set; }
        public string PDFFileName { get; set; }
        public string flagSignature { get; set; }
        public Nullable<System.DateTime> dateCertifiedLabelGenerated { get; set; }
    
        public virtual CELetter CELetter { get; set; }
        public virtual LookupEmployee LookupEmployee { get; set; }
        public virtual LookupEmployee LookupEmployee1 { get; set; }
    }
}
