//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CertifiedLabel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CertifiedLabel
    {
        public int CertifiedLabelLabelID { get; set; }
        public string CertifiedNumber { get; set; }
        public string ApplicationName { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> SectionID { get; set; }
        public string ReferenceNumber { get; set; }
        public Nullable<int> ReferenceID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<bool> IsReceived { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Section Section { get; set; }
    }
}
