//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CertifiedLabel.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CityViewEntities1 : DbContext
    {
        public CityViewEntities1()
            : base("name=CityViewEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CECase> CECases { get; set; }
        public virtual DbSet<CELetter> CELetters { get; set; }
        public virtual DbSet<CELetterRecipient> CELetterRecipients { get; set; }
        public virtual DbSet<LookupCESectorsInfo> LookupCESectorsInfoes { get; set; }
        public virtual DbSet<LookupEmployee> LookupEmployees { get; set; }
    }
}
