//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CertifiedLabel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LookupCESectorsInfo
    {
        public Nullable<int> CESectorID { get; set; }
        public string Desc { get; set; }
        public string CESectorAddress { get; set; }
        public string CESectorPhone { get; set; }
        public string Code { get; set; }
        public byte[] C_TimeStamp { get; set; }
        public string DepartmentID { get; set; }
        public string SectorAddress { get; set; }
        public string SectorCity { get; set; }
        public string SectorState { get; set; }
        public string SectorZipCode { get; set; }
    }
}
