//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CertifiedLabel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LookupEmployee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LookupEmployee()
        {
            this.CECases = new HashSet<CECase>();
            this.CECases1 = new HashSet<CECase>();
            this.CELetters = new HashSet<CELetter>();
            this.CELetters1 = new HashSet<CELetter>();
            this.CELetters2 = new HashSet<CELetter>();
            this.CELetters3 = new HashSet<CELetter>();
            this.CELetterRecipients = new HashSet<CELetterRecipient>();
            this.CELetterRecipients1 = new HashSet<CELetterRecipient>();
        }
    
        public string Desc { get; set; }
        public string Code { get; set; }
        public byte[] C_TimeStamp { get; set; }
        public string SignaturePath { get; set; }
        public string Email { get; set; }
        public string Title { get; set; }
        public string PhoneExt { get; set; }
        public string PhoneCell { get; set; }
        public string Phone { get; set; }
        public string PhoneFax { get; set; }
        public string Filter { get; set; }
        public Nullable<short> OfficeLocation { get; set; }
        public Nullable<bool> flagActive { get; set; }
        public string Position { get; set; }
        public string LetterAdmin { get; set; }
        public string Department { get; set; }
        public string HistCode { get; set; }
        public Nullable<int> CESECTID { get; set; }
        public string CSRCode { get; set; }
        public string Compare { get; set; }
        public string Division { get; set; }
        public Nullable<bool> flagNotarizeSWTL { get; set; }
        public Nullable<bool> flagNotarizeNOV { get; set; }
        public string NotarySignaturePath { get; set; }
        public Nullable<bool> flagNotarizeTWL { get; set; }
        public Nullable<bool> flagNotarizeTAH { get; set; }
        public Nullable<System.DateTime> ExpiresDate { get; set; }
        public Nullable<bool> flagNotarizeSWTS { get; set; }
        public Nullable<bool> flagNotarizeSUM { get; set; }
        public Nullable<bool> flagNotarizeTKT { get; set; }
        public Nullable<bool> flagNotarizeTSM { get; set; }
        public string NotaryName { get; set; }
        public Nullable<bool> flagNotarizeSWT { get; set; }
        public Nullable<bool> flagNotarizeLOT { get; set; }
        public string CommissionNumber { get; set; }
        public Nullable<bool> flagCertifyLC { get; set; }
        public Nullable<bool> flagCertifyCESW { get; set; }
        public Nullable<bool> flagCertifySWSW { get; set; }
        public Nullable<bool> flagClearTKT { get; set; }
        public Nullable<bool> flagClearCESW { get; set; }
        public Nullable<bool> flagCertifyTKT { get; set; }
        public Nullable<bool> flagClearSWSW { get; set; }
        public Nullable<bool> flagClearLC { get; set; }
        public Nullable<bool> flagClearNOV { get; set; }
        public Nullable<bool> flagCertifyNOV { get; set; }
        public Nullable<bool> flag4050 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CECase> CECases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CECase> CECases1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CELetter> CELetters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CELetter> CELetters1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CELetter> CELetters2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CELetter> CELetters3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CELetterRecipient> CELetterRecipients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CELetterRecipient> CELetterRecipients1 { get; set; }
    }
}
